#!/usr/bin/env bash
#Update apps or programs
#Install nginx web server
#Install in your server
#listen in the port 80
#restarting nginx
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
rm /var/www/html/
echo 'Holberton School' > /var/www/html/index.html
service nginx start