#!/usr/bin/env bash
#  your Nginx server to have a custom 404 contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
printf "Ceci n'est pas une page\\n" > /var/www/html/404.html
sed -i '/listen 80 default_server/a \\terror_page 404 /404.html;' /etc/nginx//etc/nginx/sites-available/default
sudo service nginx restart
