#!/usr/bin/env bash
# custom HTTP header 
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
PATHS="/etc/nginx/sites-available/default"
sudo sed -i "46i \\\tadd_header X-Served-By $HOSTNAME;" $PATHS
sudo service nginx restart
