#!/usr/bin/env bash
#print message, validate loop wule, if
iter=1
while [ $iter -le 10 ]
do
    echo "Holberton School"
    iter=$((iter + 1))
    if [ $iter -ge 11 ]; then
        echo "Hi"
    fi
done
