#!/usr/bin/env bash
#print message, validate loop while, if, elif, else
iter=1
while [ $iter -le 20 ]
do
    echo $iter
    iter=$((iter + 1))
    case $iter in
    [5]*)
        echo "bad luck from China"
        ;;
    10*)
        echo "bad luck from Japan"
        ;;
    18*)
        echo "bad luck from Italy"
        ;;
    esac
done