#!/usr/bin/env bash
#print message, validate loop while, if, elif, else
iter=1
while [ $iter -le 20 ]
do
    echo $iter
    iter=$((iter + 1))
    if [ $iter -eq 5 ];
        then
        echo "bad luck from China"
    elif [ $iter -eq 10  ];
        then
        echo "bad luck from Japan"
    elif [ $iter -eq 18  ];
        then
        echo "bad luck from Italy"
    fi
done