#!/usr/bin/env bash
# Install ufw and configurate
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow OpenSSh #ssh
sudo ufw allow 80 #http
sudo ufw allow 443 #https
sudo ufw enable
sudo ufw status verbose
