#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
cp /etc/hosts hoststmp
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hoststmp
cp -f hoststmp /etc/hosts
