#!/usr/bin/env bash
# Run nginex as nginx
sudo pkill "apache2"
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
