#!/usr/bin/env bash
# Run nginex as nginx
pkill "apache2"
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod u+r /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
